name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch data
        run: python ena-explorer/fetch_data.py

      - name: Build
        run: cd ena-explorer && wasm-pack build --out-dir pkg

      - name: Move data
        run: mv ena_data.json ena-explorer/pkg

      - name: Copy index.html
        run: cp ena-explorer/index.html ena-explorer/pkg/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ena-explorer/pkg
